def user_query(user_input:str) -> str:
    return f"""

The data is stored in a SQLite database with one table. The table contains all the details about expense extracted from the bill. Calling that one table as report

Table: ocr_line_items

Below are the column labels in the table:
-`Invoice_No`: Unique id number of each bill
-`line_item_id`: Serial number for expense within the bill. A bill can have mulitple serial number
-`Issue_Date`: Date of issuing the bill and is usually stored in DD-MM-YYYY format
-`billed_to`: Bill created in the name of user or the purchaser
-`billed_by`: Bill generated by the shop or from where it is purchased
-`Description`: Description of the expense 
-`Category`: Each description is categorized into certain category. 
-`Amount`: Expense incured on line_item_id
-`Grand_Total`: Total Expense against the invoice_no
-`source_file`: image_file id 


Use only valid SQLite syntax
---


    
    
---
Write the correct SQLite query for:

Question: {user_input}

Return only the valid SQLite query. Do not prefix or explain anything. Do not say 'Here is the query:' or any other sentence. Just start from SELECT or PRAGMA.
""" 
    